-- Initial DigiBank database schema.
--
-- This migration creates the customer, bank account, and transfer tables used by the workshop API.
-- Constraints protect important business rules at the database layer: unique customer identifiers,
-- non-negative account balances, valid enum values, positive transfer amounts, and different source and
-- target accounts. These checks back up the Java validation and service rules.
--
CREATE TABLE customers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name VARCHAR(100) NOT NULL,
    last_name VARCHAR(100) NOT NULL,
    email VARCHAR(254) NOT NULL,
    identity_number VARCHAR(100) NOT NULL,
    status VARCHAR(20) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uk_customers_email UNIQUE (email),
    CONSTRAINT uk_customers_identity_number UNIQUE (identity_number),
    CONSTRAINT ck_customers_status CHECK (status IN ('ACTIVE', 'INACTIVE', 'SUSPENDED'))
);

CREATE TABLE bank_accounts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_number VARCHAR(12) NOT NULL,
    balance DECIMAL(19, 2) NOT NULL,
    currency VARCHAR(3) NOT NULL,
    account_type VARCHAR(20) NOT NULL,
    status VARCHAR(20) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    customer_id BIGINT NOT NULL,
    CONSTRAINT uk_bank_accounts_account_number UNIQUE (account_number),
    CONSTRAINT fk_bank_accounts_customer FOREIGN KEY (customer_id) REFERENCES customers (id),
    CONSTRAINT ck_bank_accounts_balance CHECK (balance >= 0),
    CONSTRAINT ck_bank_accounts_number_length CHECK (CHAR_LENGTH(account_number) = 12),
    CONSTRAINT ck_bank_accounts_currency_length CHECK (CHAR_LENGTH(currency) = 3),
    CONSTRAINT ck_bank_accounts_type CHECK (account_type IN ('CURRENT', 'SAVINGS')),
    CONSTRAINT ck_bank_accounts_status CHECK (status IN ('ACTIVE', 'FROZEN', 'CLOSED'))
);

CREATE INDEX idx_bank_accounts_customer_id ON bank_accounts (customer_id);

CREATE TABLE transfers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    transfer_reference VARCHAR(64) NOT NULL,
    source_account_number VARCHAR(12) NOT NULL,
    target_account_number VARCHAR(12) NOT NULL,
    amount DECIMAL(19, 2) NOT NULL,
    status VARCHAR(20) NOT NULL,
    execution_date TIMESTAMP WITH TIME ZONE NOT NULL,
    description VARCHAR(255),
    CONSTRAINT uk_transfers_reference UNIQUE (transfer_reference),
    CONSTRAINT fk_transfers_source_account FOREIGN KEY (source_account_number)
        REFERENCES bank_accounts (account_number),
    CONSTRAINT fk_transfers_target_account FOREIGN KEY (target_account_number)
        REFERENCES bank_accounts (account_number),
    CONSTRAINT ck_transfers_amount CHECK (amount > 0),
    CONSTRAINT ck_transfers_accounts_differ CHECK (source_account_number <> target_account_number),
    CONSTRAINT ck_transfers_status CHECK (status IN ('PENDING', 'SUCCESS', 'FAILED'))
);

CREATE INDEX idx_transfers_source_account ON transfers (source_account_number);
CREATE INDEX idx_transfers_target_account ON transfers (target_account_number);
CREATE INDEX idx_transfers_execution_date ON transfers (execution_date);
