package com.m2ibank.transfer.dto;

import com.m2ibank.transfer.entity.TransferStatus;
import io.swagger.v3.oas.annotations.media.Schema;
import java.math.BigDecimal;
import java.time.Instant;

/**
 * Response body returned after a transfer is created or read.
 *
 * <p>The record contains the transfer id, public reference, source and target account numbers, amount,
 * final status, execution time, and optional description. It mirrors the immutable audit fields stored
 * by the {@code Transfer} entity.</p>
 */
@Schema(description = "Public transfer details returned after execution or history lookup.")
public record TransferResponseDto(
        @Schema(description = "Internal transfer identifier.", example = "1")
        Long id,

        @Schema(description = "Public transfer reference generated by the server.",
                example = "TRF-69DAD59F-85B4-41F3-AB55-ED2E50D3F18E")
        String transferReference,

        @Schema(description = "12-digit account number debited by the transfer.", example = "100000000001")
        String sourceAccountNumber,

        @Schema(description = "12-digit account number credited by the transfer.", example = "100000000002")
        String targetAccountNumber,

        @Schema(description = "Transferred amount.", example = "100.00")
        BigDecimal amount,

        @Schema(description = "Final transfer status.", example = "SUCCESS")
        TransferStatus status,

        @Schema(description = "Time when the transfer was executed.", example = "2026-09-03T11:46:47Z")
        Instant executionDate,

        @Schema(description = "Optional note supplied when the transfer was created.",
                example = "Monthly savings transfer")
        String description) {
}
